services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network

  web-app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Recipe
      - MONGO_DB=Recipe
      - OPENAI_API_KEY = $${{ secrets.OPENAIKEY }}
    ports:
      - "5000:5000"
    networks:
      - network
    depends_on:
      - mongodb

networks:
  network:
    driver: bridge